/**
 * Legs, clusters and cost, checked against goldens generated by running the LIVE PAGE's own
 * functions over the live page's own data (`tools/gen-golden.mjs`). Nothing in
 * `legacy-*.json` was produced by the code under test.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { europe2026, golden } from './fixture.ts';
import {
  computeLegs, focusCluster, fitSpanKm, rawSpanKm, mapBounds, MIN_SPAN_KM, stopPoints,
  rollUpCost, formatRange, haversine, dayMovingMinutes,
} from '../src/index.ts';

type LegacyLeg = { mode: string; mins: number; km: number | null } | null;

test('computeLegs reproduces the live app for all 16 days, mode, minutes and kilometres', () => {
  const { trip } = europe2026();
  const g = golden<{ legs: Record<string, LegacyLeg[]> }>('legacy-legs.json');
  let compared = 0;
  for (const day of trip.days) {
    const key = day.date.slice(5); // legacy ids are "MM-DD"
    const expected = g.legs[key];
    assert.ok(expected, `no golden legs for ${key}`);
    const actual = computeLegs(day, trip);
    assert.equal(actual.length, expected.length, `${key}: leg count`);
    for (let i = 0; i < expected.length; i++) {
      const e = expected[i];
      const a = actual[i];
      if (e === null) {
        assert.equal(a, null, `${key}[${i}] should have no leg`);
        continue;
      }
      assert.ok(a, `${key}[${i}] missing leg`);
      assert.equal(a.mode, e.mode, `${key}[${i}] mode`);
      assert.equal(a.mins, e.mins, `${key}[${i}] minutes`);
      if (e.km === null) assert.equal(a.km, null, `${key}[${i}] km`);
      else assert.ok(Math.abs((a.km as number) - e.km) < 1e-6, `${key}[${i}] km ${a.km} vs ${e.km}`);
      compared++;
    }
  }
  assert.ok(compared > 80, `expected to compare most of the 112 stops, compared ${compared}`);
});

test('Aug 12 FlixBus leg is 245 minutes ARRIVING at Split, not departing Dubrovnik', () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-12');
  assert.ok(day);
  const i = day.stops.findIndex((s) => s.name.startsWith('FlixBus → Split'));
  const legs = computeLegs(day, trip);
  assert.equal(legs[i]?.mins, 245);
  assert.equal(legs[i]?.mode, 'bus');
  assert.equal(legs[i]?.source, 'override');
  assert.equal(day.stops[i].arrival?.mins, 245, 'the override lives on the ARRIVING stop');
});

test('focusCluster matches the live app: split flag, group sizes and focus membership', () => {
  const { trip } = europe2026();
  const g = golden<{ clusters: Record<string, { split: boolean; groupSizes: number[]; focusNames: string[]; focusSpanKm: number }> }>(
    'legacy-clusters.json',
  );
  for (const day of trip.days) {
    const key = day.date.slice(5);
    const e = g.clusters[key];
    const a = focusCluster(day.stops, trip);
    assert.equal(a.split, e.split, `${key}: split`);
    assert.deepEqual(a.groups.map((x) => x.length), e.groupSizes, `${key}: group sizes`);
    assert.deepEqual(a.focus.map((s) => s.name), e.focusNames, `${key}: focus membership`);
    assert.ok(Math.abs(a.spanKm - e.focusSpanKm) < 1e-6, `${key}: focus span`);
  }
});

test('Aug 8 spans 621 km but focuses on the Vienna cluster', () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-08');
  assert.ok(day);
  const all = stopPoints(day.stops, trip);
  assert.ok(rawSpanKm(all) > 600, 'the whole day really does span >600 km');
  const foc = focusCluster(day.stops, trip);
  assert.equal(foc.split, true);
  assert.ok(foc.focus.length >= 5, 'the Vienna cluster holds the bulk of the day');
  for (const s of foc.focus) {
    const at = stopPoints([s], trip)[0];
    assert.ok(haversine(at, { lat: 48.2082, lng: 16.3738 }) < 35, `${s.name} is not in Vienna`);
  }
});

test('a day on one street never fits below MIN_SPAN_KM', () => {
  const { trip } = europe2026();
  for (const day of trip.days) {
    const foc = focusCluster(day.stops, trip);
    const span = fitSpanKm(stopPoints(foc.focus, trip));
    assert.ok(span >= MIN_SPAN_KM, `${day.id} fit span ${span} below the guard`);
  }
  // Two pins 40 m apart still produce a usable box.
  const tight = [
    { lat: 48.2082, lng: 16.3738 },
    { lat: 48.20824, lng: 16.37384 },
  ];
  assert.ok(rawSpanKm(tight) < 0.1);
  assert.equal(fitSpanKm(tight), MIN_SPAN_KM);
  const b = mapBounds(tight);
  assert.equal(b.clamped, true);
  assert.ok(b.north > b.south && b.east > b.west);
});

test('mapBounds refuses to invent a box for no points', () => {
  const b = mapBounds([]);
  assert.equal(b.empty, true);
});

test('rollUpCost: badge-only "free" stops contribute nothing', () => {
  const { trip } = europe2026();
  const freeStops = trip.days.flatMap((d) => d.stops).filter((s) => s.flags.includes('free'));
  assert.ok(freeStops.length > 0);
  for (const s of freeStops) assert.equal(s.cost, null, `${s.name} should carry no cost, only a badge`);
  const roll = rollUpCost(freeStops);
  assert.deepEqual(roll.byCurrency, {});
});

/**
 * Day-cost parity with the live page, day by day, with every divergence NAMED.
 *
 * ROADMAP's acceptance criterion says "`rollUpCost(day)` reproduces the live app's
 * `dayCost()` string for all 16 days". **It does not, and it must not.** The real figure is
 * **6 of 16 exact, 10 divergent**, and the criterion contradicts ARCHITECTURE §2.6, which
 * is the section that exists precisely to stop the live page's four money defects being
 * carried forward. Where the two disagree, §2.6 wins and the criterion is wrong.
 *
 * The previous version of this test asserted `exact === 6` and waved the other ten through
 * as "divergent — see BUILD-NOTES", where BUILD-NOTES said nothing. A count with no reason
 * behind it is not an assertion. So: each of the ten is classified below, and the test
 * proves the classification against the data rather than taking it on trust. `exact === 6`
 * is now a CONSEQUENCE (16 − 10), not the claim. BUILD-NOTES §1, KD-3.
 *
 * The four §2.6 defects, and which days they land on:
 *
 *   `multi_currency`    — the live page hand-converted "~450 CZK" to `c:[18,18]` and
 *                         "$159.98pp" to `c:[160,160]` at an unrecorded rate on an
 *                         unrecorded date. Core keeps each currency separate and refuses to
 *                         invent a rate, so its EUR subtotal is legitimately smaller.
 *   `per_party_basis`   — "$573.25 total" is a party total for 5 adults; the live page adds
 *                         it to per-person amounts. Core keeps the basis and warns.
 *   `split_product`     — "Gardens free · palace €15–24" is two products in one string;
 *                         `c:[0,24]` encodes it as one €0–24 range. Core splits it, so the
 *                         low end is the palace's €15, not €0.
 *   `c_pair_vs_display` — the hand-written `c` pair disagrees with its own display string
 *                         (Aug 14's €14.49 FlixBus fare carries `c:[14,15]`). Core reads
 *                         the display string, which is the number on the ticket.
 */
type Divergence = 'multi_currency' | 'per_party_basis' | 'split_product' | 'c_pair_vs_display';

const DIVERGENT: Record<string, { why: Divergence; note: string }> = {
  '2026-08-09': { why: 'split_product', note: 'Schönbrunn "Gardens free · palace €15–24" — legacy c:[0,24], core €15–24 + a free item' },
  '2026-08-13': { why: 'multi_currency', note: '$159.98pp speedboat kept in USD, not folded into EUR at a made-up rate' },
  '2026-08-14': { why: 'c_pair_vs_display', note: 'FlixBus €14.49 carries c:[14,15]; core reads the €14.49 on the ticket' },
  '2026-08-15': { why: 'multi_currency', note: '~100 CZK airport bus kept in CZK' },
  '2026-08-16': { why: 'multi_currency', note: '~550 CZK Josefov combined ticket kept in CZK' },
  '2026-08-17': { why: 'multi_currency', note: '~450 CZK Prague Castle main circuit kept in CZK' },
  '2026-08-18': { why: 'multi_currency', note: '~100 CZK transfer kept in CZK' },
  '2026-08-19': { why: 'per_party_basis', note: '$573.25 Danube cruise is a party total in USD, on both counts not summable' },
  '2026-08-21': { why: 'multi_currency', note: 'London GBP kept in GBP' },
  '2026-08-22': { why: 'multi_currency', note: 'London GBP kept in GBP; the day has no EUR amount at all' },
};

test('day-cost parity with the live app is 6 of 16 exact, and each of the other 10 is a §2.6 money defect the live page had', () => {
  const { trip } = europe2026();
  const legacy = golden<{ dayCost: Record<string, string | null> }>('legacy-daycost.json').dayCost;
  const expected = golden<{ days: Record<string, { parity: string; legacyString: string | null }> }>('core-daycost.json').days;

  const exactDays: string[] = [];
  const divergentDays: string[] = [];

  for (const day of trip.days) {
    const roll = rollUpCost(day.stops);
    const eur = roll.byCurrency.EUR;
    const coreString = eur ? `≈ ${formatRange('EUR', eur.lo, eur.hi)}` : null;

    // The golden must still be the live page's own output, not ours.
    assert.equal(legacy[day.date.slice(5)], expected[day.id].legacyString, `${day.id}: golden legacy string drifted`);

    if (coreString === expected[day.id].legacyString) {
      exactDays.push(day.id);
      assert.equal(expected[day.id].parity, 'exact', day.id);
      assert.equal(DIVERGENT[day.id], undefined, `${day.id} is listed as divergent but matches exactly`);
      continue;
    }

    divergentDays.push(day.id);
    assert.equal(expected[day.id].parity, 'divergent', day.id);
    const claim = DIVERGENT[day.id];
    assert.ok(claim, `${day.id} diverges from the live app and NOTHING here says why. Classify it or fix it.`);

    // Prove the stated reason against the data, so the table cannot rot into a comment.
    const currencies = Object.keys(roll.byCurrency);
    const amounts = day.stops.flatMap((s) => s.cost?.amounts ?? []);
    const bases = new Set(amounts.map((a) => a.basis));
    const splitProducts = day.stops.filter((s) => (s.cost?.amounts.length ?? 0) > 1);

    if (claim.why === 'multi_currency') {
      assert.ok(currencies.some((c) => c !== 'EUR'),
        `${day.id}: claimed multi_currency but the day is EUR-only (${currencies.join(',')})`);
      // Against a EUR target, every non-EUR currency is unconvertible — which is exactly
      // what the live page papered over with a hand-picked rate.
      assert.ok(rollUpCost(day.stops, { target: 'EUR' }).missingRates.length > 0,
        `${day.id}: claimed multi_currency but nothing is unconvertible against EUR`);
    } else if (claim.why === 'per_party_basis') {
      assert.ok(bases.has('per_party') && bases.has('per_person'),
        `${day.id}: claimed per_party_basis but the bases are ${[...bases].join(',')}`);
    } else if (claim.why === 'split_product') {
      assert.equal(splitProducts.length > 0, true, `${day.id}: claimed split_product but no stop carries two amounts`);
    } else {
      // c_pair_vs_display: single currency, single basis, no split product — the ONLY
      // remaining explanation is that the legacy numeric pair contradicted its own string.
      assert.deepEqual(currencies, ['EUR'], `${day.id}: claimed c_pair_vs_display but is multi-currency`);
      assert.deepEqual([...bases], ['per_person'], `${day.id}: claimed c_pair_vs_display but mixes basis`);
      assert.equal(splitProducts.length, 0, `${day.id}: claimed c_pair_vs_display but has a split product`);
      assert.ok(amounts.some((a) => !Number.isInteger(a.lo) || !Number.isInteger(a.hi)),
        `${day.id}: claimed c_pair_vs_display but every amount is a whole number`);
    }
  }

  assert.deepEqual(divergentDays, Object.keys(DIVERGENT), 'the set of divergent days moved');
  assert.equal(divergentDays.length, 10);
  assert.equal(exactDays.length, 6,
    'ROADMAP asks for 16/16. It is 6/16 by design — see the header above and BUILD-NOTES §1, ' +
    'KD-3. If this number moves, one of the ten explanations changed.');
  assert.equal(exactDays.length + divergentDays.length, 16);
});

test('CZK and GBP costs are reported per currency and never silently converted', () => {
  const { trip } = europe2026();
  const prague = trip.days.find((d) => d.id === '2026-08-17');
  assert.ok(prague);
  const roll = rollUpCost(prague.stops, { target: 'EUR' });
  assert.ok(roll.byCurrency.CZK, 'CZK kept as CZK');
  assert.equal(roll.converted, null, 'core must not invent a rate');
  assert.ok(roll.missingRates.includes('CZK'));
  const london = trip.days.find((d) => d.id === '2026-08-22');
  const gbp = rollUpCost(london!.stops, { target: 'EUR' });
  assert.ok(gbp.byCurrency.GBP);
  assert.ok(gbp.missingRates.includes('GBP'));
});

test("the Danube cruise's per-party price raises a basis warning instead of being added blind", () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-19');
  assert.ok(day);
  const cruise = day.stops.find((s) => s.name.startsWith('Board the Danube'));
  assert.equal(cruise?.cost?.amounts[0].basis, 'per_party');
  const roll = rollUpCost(day.stops);
  assert.equal(roll.basisWarnings.length, 0, 'USD has only the one party amount on this day');
  const mixed = rollUpCost([...day.stops, { ...cruise!, id: 'x', cost: { amounts: [{ lo: 10, hi: 10, currency: 'USD', basis: 'per_person' }], display: '$10pp' } }]);
  assert.equal(mixed.basisWarnings.length, 1);
  assert.match(mixed.basisWarnings[0], /per-person and per-party/);
});

test('dayMovingMinutes sums the legs and nothing else', () => {
  const { trip } = europe2026();
  for (const day of trip.days) {
    const legs = computeLegs(day, trip);
    assert.equal(dayMovingMinutes(day, trip), legs.reduce((n, l) => n + (l ? l.mins : 0), 0));
  }
});
