/**
 * Legs, clusters and cost, checked against goldens generated by running the LIVE PAGE's own
 * functions over the live page's own data (`tools/gen-golden.mjs`). Nothing in
 * `legacy-*.json` was produced by the code under test.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { europe2026, golden } from './fixture.ts';
import {
  computeLegs, focusCluster, fitSpanKm, rawSpanKm, mapBounds, MIN_SPAN_KM, stopPoints,
  rollUpCost, formatRange, haversine, dayMovingMinutes,
} from '../src/index.ts';

type LegacyLeg = { mode: string; mins: number; km: number | null } | null;

test('computeLegs reproduces the live app for all 16 days, mode, minutes and kilometres', () => {
  const { trip } = europe2026();
  const g = golden<{ legs: Record<string, LegacyLeg[]> }>('legacy-legs.json');
  let compared = 0;
  for (const day of trip.days) {
    const key = day.date.slice(5); // legacy ids are "MM-DD"
    const expected = g.legs[key];
    assert.ok(expected, `no golden legs for ${key}`);
    const actual = computeLegs(day, trip);
    assert.equal(actual.length, expected.length, `${key}: leg count`);
    for (let i = 0; i < expected.length; i++) {
      const e = expected[i];
      const a = actual[i];
      if (e === null) {
        assert.equal(a, null, `${key}[${i}] should have no leg`);
        continue;
      }
      assert.ok(a, `${key}[${i}] missing leg`);
      assert.equal(a.mode, e.mode, `${key}[${i}] mode`);
      assert.equal(a.mins, e.mins, `${key}[${i}] minutes`);
      if (e.km === null) assert.equal(a.km, null, `${key}[${i}] km`);
      else assert.ok(Math.abs((a.km as number) - e.km) < 1e-6, `${key}[${i}] km ${a.km} vs ${e.km}`);
      compared++;
    }
  }
  assert.ok(compared > 80, `expected to compare most of the 112 stops, compared ${compared}`);
});

test('Aug 12 FlixBus leg is 245 minutes ARRIVING at Split, not departing Dubrovnik', () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-12');
  assert.ok(day);
  const i = day.stops.findIndex((s) => s.name.startsWith('FlixBus → Split'));
  const legs = computeLegs(day, trip);
  assert.equal(legs[i]?.mins, 245);
  assert.equal(legs[i]?.mode, 'bus');
  assert.equal(legs[i]?.source, 'override');
  assert.equal(day.stops[i].arrival?.mins, 245, 'the override lives on the ARRIVING stop');
});

test('focusCluster matches the live app: split flag, group sizes and focus membership', () => {
  const { trip } = europe2026();
  const g = golden<{ clusters: Record<string, { split: boolean; groupSizes: number[]; focusNames: string[]; focusSpanKm: number }> }>(
    'legacy-clusters.json',
  );
  for (const day of trip.days) {
    const key = day.date.slice(5);
    const e = g.clusters[key];
    const a = focusCluster(day.stops, trip);
    assert.equal(a.split, e.split, `${key}: split`);
    assert.deepEqual(a.groups.map((x) => x.length), e.groupSizes, `${key}: group sizes`);
    assert.deepEqual(a.focus.map((s) => s.name), e.focusNames, `${key}: focus membership`);
    assert.ok(Math.abs(a.spanKm - e.focusSpanKm) < 1e-6, `${key}: focus span`);
  }
});

test('Aug 8 spans 621 km but focuses on the Vienna cluster', () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-08');
  assert.ok(day);
  const all = stopPoints(day.stops, trip);
  assert.ok(rawSpanKm(all) > 600, 'the whole day really does span >600 km');
  const foc = focusCluster(day.stops, trip);
  assert.equal(foc.split, true);
  assert.ok(foc.focus.length >= 5, 'the Vienna cluster holds the bulk of the day');
  for (const s of foc.focus) {
    const at = stopPoints([s], trip)[0];
    assert.ok(haversine(at, { lat: 48.2082, lng: 16.3738 }) < 35, `${s.name} is not in Vienna`);
  }
});

test('a day on one street never fits below MIN_SPAN_KM', () => {
  const { trip } = europe2026();
  for (const day of trip.days) {
    const foc = focusCluster(day.stops, trip);
    const span = fitSpanKm(stopPoints(foc.focus, trip));
    assert.ok(span >= MIN_SPAN_KM, `${day.id} fit span ${span} below the guard`);
  }
  // Two pins 40 m apart still produce a usable box.
  const tight = [
    { lat: 48.2082, lng: 16.3738 },
    { lat: 48.20824, lng: 16.37384 },
  ];
  assert.ok(rawSpanKm(tight) < 0.1);
  assert.equal(fitSpanKm(tight), MIN_SPAN_KM);
  const b = mapBounds(tight);
  assert.equal(b.clamped, true);
  assert.ok(b.north > b.south && b.east > b.west);
});

test('mapBounds refuses to invent a box for no points', () => {
  const b = mapBounds([]);
  assert.equal(b.empty, true);
});

test('rollUpCost: badge-only "free" stops contribute nothing', () => {
  const { trip } = europe2026();
  const freeStops = trip.days.flatMap((d) => d.stops).filter((s) => s.flags.includes('free'));
  assert.ok(freeStops.length > 0);
  for (const s of freeStops) assert.equal(s.cost, null, `${s.name} should carry no cost, only a badge`);
  const roll = rollUpCost(freeStops);
  assert.deepEqual(roll.byCurrency, {});
});

test('rollUpCost matches the live dayCost for every EUR-only day, and diverges only where §2.6 says it must', () => {
  const { trip } = europe2026();
  const legacy = golden<{ dayCost: Record<string, string | null> }>('legacy-daycost.json').dayCost;
  const expected = golden<{ days: Record<string, { parity: string; legacyString: string | null }> }>('core-daycost.json').days;
  let exact = 0;
  for (const day of trip.days) {
    const roll = rollUpCost(day.stops);
    const eur = roll.byCurrency.EUR;
    const coreString = eur ? `≈ ${formatRange('EUR', eur.lo, eur.hi)}` : null;
    assert.equal(legacy[day.date.slice(5)], expected[day.id].legacyString, `${day.id}: golden legacy string drifted`);
    if (coreString === expected[day.id].legacyString) {
      exact++;
      assert.equal(expected[day.id].parity, 'exact', `${day.id}`);
    } else {
      assert.equal(expected[day.id].parity, 'divergent', `${day.id} unexpectedly diverges — see BUILD-NOTES`);
    }
  }
  assert.equal(exact, 6, 'the six EUR-only, single-product days must match the live app exactly');
});

test('CZK and GBP costs are reported per currency and never silently converted', () => {
  const { trip } = europe2026();
  const prague = trip.days.find((d) => d.id === '2026-08-17');
  assert.ok(prague);
  const roll = rollUpCost(prague.stops, { target: 'EUR' });
  assert.ok(roll.byCurrency.CZK, 'CZK kept as CZK');
  assert.equal(roll.converted, null, 'core must not invent a rate');
  assert.ok(roll.missingRates.includes('CZK'));
  const london = trip.days.find((d) => d.id === '2026-08-22');
  const gbp = rollUpCost(london!.stops, { target: 'EUR' });
  assert.ok(gbp.byCurrency.GBP);
  assert.ok(gbp.missingRates.includes('GBP'));
});

test("the Danube cruise's per-party price raises a basis warning instead of being added blind", () => {
  const { trip } = europe2026();
  const day = trip.days.find((d) => d.id === '2026-08-19');
  assert.ok(day);
  const cruise = day.stops.find((s) => s.name.startsWith('Board the Danube'));
  assert.equal(cruise?.cost?.amounts[0].basis, 'per_party');
  const roll = rollUpCost(day.stops);
  assert.equal(roll.basisWarnings.length, 0, 'USD has only the one party amount on this day');
  const mixed = rollUpCost([...day.stops, { ...cruise!, id: 'x', cost: { amounts: [{ lo: 10, hi: 10, currency: 'USD', basis: 'per_person' }], display: '$10pp' } }]);
  assert.equal(mixed.basisWarnings.length, 1);
  assert.match(mixed.basisWarnings[0], /per-person and per-party/);
});

test('dayMovingMinutes sums the legs and nothing else', () => {
  const { trip } = europe2026();
  for (const day of trip.days) {
    const legs = computeLegs(day, trip);
    assert.equal(dayMovingMinutes(day, trip), legs.reduce((n, l) => n + (l ? l.mins : 0), 0));
  }
});
