/**
 * Legs (ARCHITECTURE §2.5) — a byte-exact port of the live planner's `legBetween`.
 *
 * The thresholds, the speeds, the `Math.max` floors and the `+6` / `+5` fudges are all
 * reproduced exactly; `fixtures/golden/legacy-legs.json` is generated by running the live
 * page's own function over its own data, and these must agree for all 16 days.
 *
 * `Stop.arrival` describes the leg INTO the stop — the single easiest thing in the model
 * to implement backwards.
 */
import type { Day, Leg, Stop, Trip } from '../model/types.ts';
import { haversine, stopLatLng } from './geo.ts';

/**
 * The leg into `stop` from `prev`. Pure.
 *
 * @returns null when there is nothing to draw: no previous stop and no override, a
 *          missing coordinate, or a hop shorter than 120 m.
 */
export function legBetween(prev: Stop | null, stop: Stop, trip: Trip): Leg | null {
  const pAt = prev ? stopLatLng(prev, trip) : null;
  const sAt = stopLatLng(stop, trip);
  if (stop.arrival) {
    const km = pAt && sAt ? haversine(pAt, sAt) : null;
    return {
      mode: stop.arrival.mode,
      mins: stop.arrival.mins,
      km,
      source: 'override',
      ...(stop.arrival.label ? { label: stop.arrival.label } : {}),
    };
  }
  if (!prev || !pAt || !sAt) return null;
  const km = haversine(pAt, sAt);
  if (km < 0.12) return null;
  if (km <= 1.6) {
    return { mode: 'walk', mins: Math.max(2, Math.round(((km * 1.35) / 4.8) * 60)), km, source: 'estimate' };
  }
  if (km <= 9) {
    return { mode: 'transit', mins: Math.max(8, Math.round(((km * 1.25) / 17) * 60) + 6), km, source: 'estimate' };
  }
  return { mode: 'taxi', mins: Math.round(((km * 1.2) / 50) * 60) + 5, km, source: 'estimate' };
}

/**
 * All legs of a day, index-aligned with `day.stops` (element 0 is the leg into stop 0,
 * which is null unless stop 0 carries an `arrival` override). Pure.
 */
export function computeLegs(day: Day, trip: Trip): (Leg | null)[] {
  return day.stops.map((s, i) => legBetween(i === 0 ? null : day.stops[i - 1], s, trip));
}

/** Total minutes spent moving on a day. Pure. */
export function dayMovingMinutes(day: Day, trip: Trip): number {
  return computeLegs(day, trip).reduce((n, l) => n + (l ? l.mins : 0), 0);
}

/** Total kilometres covered across a day, ignoring legs with no distance. Pure. */
export function dayDistanceKm(day: Day, trip: Trip): number {
  return computeLegs(day, trip).reduce((n, l) => n + (l && l.km ? l.km : 0), 0);
}

/** `HH:MM` → minutes since midnight; `null`/`"—"` → 99999, exactly as the live app. Pure. */
export function timeVal(t: string | null | undefined): number {
  if (!t || t === '—') return 99999;
  const m = /^(\d{1,2}):(\d{2})/.exec(t);
  return m ? Number(m[1]) * 60 + Number(m[2]) : 99999;
}

/** Formats minutes the way the live app does ("45 min", "2h 5m", "3 hr"). Pure. */
export function fmtMins(m: number): string {
  if (m < 60) return `${m} min`;
  const h = Math.floor(m / 60);
  const r = m % 60;
  return r ? `${h}h ${r}m` : `${h} hr`;
}
